apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-gmail-exporter-go.fullname" . }}-config
  labels:
    {{- include "prometheus-gmail-exporter-go.labels" . | nindent 4 }}
data:
  config.yml: |
    interval: {{ .Values.config.interval }}
    labels:
      {{- toYaml .Values.config.labels | nindent 6 }}
